In [2]:
import numpy as np

# Basic array operations

In [3]:
my_list = [1,2,3,4,5]
print(f"my list is type {type(my_list)}")
my_array = np.array(my_list)
print(f"my array is type {type(my_array)}")


my list is type <class 'list'>
my array is type <class 'numpy.ndarray'>


In [4]:
my_float_array = np.array(my_list, "float32")
print(f"my float array is type {type(my_array)}")
print (my_float_array)

my float array is type <class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]


In [5]:
my_list_of_lists = [my_list, my_list, my_list]
my_array_2d = np.array(my_list_of_lists)
print(my_array_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [6]:
my_linspace_array = np.linspace(0,1,20)
print(my_linspace_array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Basic Matrix operations

In [7]:
my_matrix = np.ones((5,6), dtype="int")
my_matrix

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [8]:
my_list = [1,2,3,4,5]
my_list_of_lists = [my_list, my_list, my_list]
my_array_2d = np.array(my_list_of_lists)
print(my_array_2d)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [9]:
my_number_matrix = np.full((6, 7), 11)
print(my_number_matrix)

[[11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]
 [11 11 11 11 11 11 11]]


In [11]:
sliced_matrix = my_number_matrix[:4,:2]
print(sliced_matrix)

[[11 11]
 [11 11]
 [11 11]
 [11 11]]


In [12]:
sliced_matrix.shape

(4, 2)